FROM docker.io/nvidia/cuda:12.8.1-cudnn-devel-ubuntu24.04

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app

RUN apt update && apt install -y \
    python3 \
    python3-venv \
    python3-pip \
    libgl1 \
    libglib2.0-0 \
    ffmpeg
RUN rm -rf /var/lib/apt/lists/*

COPY . .

RUN python3 -m venv .venv

RUN .venv/bin/pip install --no-cache-dir --upgrade pip
RUN .venv/bin/pip install --no-cache-dir torch==2.11.0 torchaudio==2.11.0 --index-url https://download.pytorch.org/whl/cu128

RUN .venv/bin/pip install --no-cache-dir -r requirements.txt

EXPOSE 6969

CMD [".venv/bin/python", "app.py", "--server-name", "0.0.0.0"]
