from __future__ import annotations

from typing import Iterable
import gradio as gr

# gr.themes.builder()
from gradio.themes.base import Base
from gradio.themes.utils import colors, fonts, sizes


class Applio(Base):
    def __init__(
        self,
        *,
        primary_hue: colors.Color | str = colors.neutral,
        secondary_hue: colors.Color | str = colors.neutral,
        neutral_hue: colors.Color | str = colors.neutral,
        spacing_size: sizes.Size | str = sizes.spacing_md,
        radius_size: sizes.Size | str = sizes.radius_md,
        text_size: sizes.Size | str = sizes.text_lg,
        font: fonts.Font | str | Iterable[fonts.Font | str] = (
            "Syne V",
            fonts.GoogleFont("Syne"),
            "ui-sans-serif",
            "system-ui",
        ),
        font_mono: fonts.Font | str | Iterable[fonts.Font | str] = (
            "ui-monospace",
            fonts.GoogleFont("Nunito Sans"),
        ),
    ):
        super().__init__(
            primary_hue=primary_hue,
            secondary_hue=secondary_hue,
            neutral_hue=neutral_hue,
            spacing_size=spacing_size,
            radius_size=radius_size,
            text_size=text_size,
            font=font,
            font_mono=font_mono,
        )
        self.name = "Applio"
        self.secondary_100 = "#ffe4e6"
        self.secondary_200 = "#fecdd3"
        self.secondary_300 = "#f2adb4"
        self.secondary_400 = "#df8e98"
        self.secondary_50 = "#fff1f2"
        self.secondary_500 = "#c96f7b"
        self.secondary_600 = "#aa5360"
        self.secondary_700 = "#8a414d"
        self.secondary_800 = "#703640"
        self.secondary_900 = "#5f3038"
        self.secondary_950 = "#35171c"

        super().set(
            # Blaise
            background_fill_primary="#181114",
            background_fill_primary_dark="#181114",
            background_fill_secondary="#201518",
            background_fill_secondary_dark="#201518",
            block_background_fill="#291B1F",
            block_background_fill_dark="#291B1F",
            block_border_color="#66434A",
            block_border_color_dark="#66434A",
            block_border_width="1px",
            block_border_width_dark="1px",
            block_info_text_color="*body_text_color_subdued",
            block_info_text_color_dark="*body_text_color_subdued",
            block_info_text_size="*text_sm",
            block_info_text_weight="400",
            block_label_background_fill="#3D282E",
            block_label_background_fill_dark="#3D282E",
            block_label_border_color="#8B514F",
            block_label_border_color_dark="#8B514F",
            block_label_border_width="1px",
            block_label_border_width_dark="1px",
            block_label_margin="0",
            block_label_padding="*spacing_sm *spacing_lg",
            block_label_radius="calc(*radius_lg - 1px) 0 calc(*radius_lg - 1px) 0",
            block_label_right_radius="0 calc(*radius_lg - 1px) 0 calc(*radius_lg - 1px)",
            block_label_shadow="*block_shadow",
            block_label_text_color="#F7EAD7",
            block_label_text_color_dark="#F7EAD7",
            block_label_text_weight="400",
            block_padding="*spacing_xl",
            block_radius="*radius_md",
            block_shadow="none",
            block_shadow_dark="none",
            block_title_background_fill="#342126",
            block_title_background_fill_dark="#342126",
            block_title_border_color="none",
            block_title_border_color_dark="none",
            block_title_border_width="0px",
            block_title_padding="*block_label_padding",
            block_title_radius="*block_label_radius",
            block_title_text_color="#F7EAD7",
            block_title_text_color_dark="#F7EAD7",
            block_title_text_size="*text_md",
            block_title_text_weight="600",
            body_background_fill="#181114",
            body_background_fill_dark="#181114",
            body_text_color="#FFF4E8",
            body_text_color_dark="#FFF4E8",
            body_text_color_subdued="#E0D1C0",
            body_text_color_subdued_dark="#E0D1C0",
            body_text_size="*text_md",
            body_text_weight="400",
            border_color_accent="#9A626B",
            border_color_accent_dark="#9A626B",
            border_color_primary="#66434A",
            border_color_primary_dark="#66434A",
            button_border_width="*input_border_width",
            button_border_width_dark="*input_border_width",
            button_cancel_background_fill="*button_secondary_background_fill",
            button_cancel_background_fill_dark="*button_secondary_background_fill",
            button_cancel_background_fill_hover="*button_cancel_background_fill",
            button_cancel_background_fill_hover_dark="*button_cancel_background_fill",
            button_cancel_border_color="*button_secondary_border_color",
            button_cancel_border_color_dark="*button_secondary_border_color",
            button_cancel_border_color_hover="*button_cancel_border_color",
            button_cancel_border_color_hover_dark="*button_cancel_border_color",
            button_cancel_text_color="#FFF4E8",
            button_cancel_text_color_dark="#FFF4E8",
            button_cancel_text_color_hover="#FFFFFF",
            button_cancel_text_color_hover_dark="#FFFFFF",
            button_large_padding="*spacing_lg calc(2 * *spacing_lg)",
            button_large_radius="*radius_lg",
            button_large_text_size="*text_lg",
            button_large_text_weight="600",
            button_primary_background_fill="#B86642",
            button_primary_background_fill_dark="#B86642",
            button_primary_background_fill_hover="#D88458",
            button_primary_background_fill_hover_dark="#D88458",
            button_primary_border_color="#C9794D",
            button_primary_border_color_dark="#C9794D",
            button_primary_border_color_hover="#E6A16D",
            button_primary_border_color_hover_dark="#E6A16D",
            button_primary_text_color="#FFFFFF",
            button_primary_text_color_dark="#FFFFFF",
            button_primary_text_color_hover="#FFFFFF",
            button_primary_text_color_hover_dark="#FFFFFF",
            button_secondary_background_fill="#2A1C21",
            button_secondary_background_fill_dark="#2A1C21",
            button_secondary_background_fill_hover="#38252B",
            button_secondary_background_fill_hover_dark="#38252B",
            button_secondary_border_color="#76505A",
            button_secondary_border_color_dark="#76505A",
            button_secondary_border_color_hover="#C07965",
            button_secondary_border_color_hover_dark="#C07965",
            button_secondary_text_color="#FFF4E8",
            button_secondary_text_color_dark="#FFF4E8",
            button_secondary_text_color_hover="*button_secondary_text_color",
            button_secondary_text_color_hover_dark="*button_secondary_text_color",
            button_small_padding="*spacing_sm calc(2 * *spacing_sm)",
            button_small_radius="*radius_lg",
            button_small_text_size="*text_md",
            button_small_text_weight="400",
            button_transition="0.3s ease all",
            checkbox_background_color="#211619",
            checkbox_background_color_dark="#211619",
            checkbox_background_color_focus="*checkbox_background_color",
            checkbox_background_color_focus_dark="*checkbox_background_color",
            checkbox_background_color_hover="*checkbox_background_color",
            checkbox_background_color_hover_dark="*checkbox_background_color",
            checkbox_background_color_selected="#B86642",
            checkbox_background_color_selected_dark="#B86642",
            checkbox_border_color="#9A626B",
            checkbox_border_color_dark="#9A626B",
            checkbox_border_color_focus="*secondary_500",
            checkbox_border_color_focus_dark="*secondary_500",
            checkbox_border_color_hover="#DF8E98",
            checkbox_border_color_hover_dark="#DF8E98",
            checkbox_border_color_selected="#C9794D",
            checkbox_border_color_selected_dark="#C9794D",
            checkbox_border_radius="*radius_sm",
            checkbox_border_width="*input_border_width",
            checkbox_border_width_dark="*input_border_width",
            checkbox_check="url(\"data:image/svg+xml,%3csvg viewBox='0 0 16 16' fill='white' xmlns='http://www.w3.org/2000/svg'%3e%3cpath d='M12.207 4.793a1 1 0 010 1.414l-5 5a1 1 0 01-1.414 0l-2-2a1 1 0 011.414-1.414L6.5 9.086l4.293-4.293a1 1 0 011.414 0z'/%3e%3c/svg%3e\")",
            checkbox_label_background_fill="transparent",
            checkbox_label_background_fill_dark="transparent",
            checkbox_label_background_fill_hover="transparent",
            checkbox_label_background_fill_hover_dark="transparent",
            checkbox_label_background_fill_selected="transparent",
            checkbox_label_background_fill_selected_dark="transparent",
            checkbox_label_border_color="transparent",
            checkbox_label_border_color_dark="transparent",
            checkbox_label_border_color_hover="transparent",
            checkbox_label_border_color_hover_dark="transparent",
            checkbox_label_border_width="transparent",
            checkbox_label_border_width_dark="transparent",
            checkbox_label_gap="*spacing_lg",
            checkbox_label_padding="*spacing_md calc(2 * *spacing_md)",
            checkbox_label_shadow="none",
            checkbox_label_text_color="*body_text_color",
            checkbox_label_text_color_dark="*body_text_color",
            checkbox_label_text_color_selected="*checkbox_label_text_color",
            checkbox_label_text_color_selected_dark="*checkbox_label_text_color",
            checkbox_label_text_size="*text_md",
            checkbox_label_text_weight="400",
            checkbox_shadow="*input_shadow",
            color_accent="#D18A58",
            color_accent_soft="#3D282E",
            color_accent_soft_dark="#3D282E",
            container_radius="*radius_xl",
            embed_radius="*radius_lg",
            error_background_fill="*background_fill_primary",
            error_background_fill_dark="*background_fill_primary",
            error_border_color="*border_color_primary",
            error_border_color_dark="*border_color_primary",
            error_border_width="1px",
            error_border_width_dark="1px",
            error_text_color="#ef4444",
            error_text_color_dark="#ef4444",
            form_gap_width="0px",
            input_background_fill="#211619",
            input_background_fill_dark="#211619",
            input_background_fill_focus="#2E1D22",
            input_background_fill_focus_dark="#2E1D22",
            input_background_fill_hover="*input_background_fill",
            input_background_fill_hover_dark="*input_background_fill",
            input_border_color="#76505A",
            input_border_color_dark="#76505A",
            input_border_color_focus="#C9794D",
            input_border_color_focus_dark="#C9794D",
            input_border_color_hover="*input_border_color",
            input_border_color_hover_dark="*input_border_color",
            input_border_width="1px",
            input_border_width_dark="1px",
            input_padding="*spacing_xl",
            input_placeholder_color="#BFB2A4",
            input_placeholder_color_dark="#BFB2A4",
            input_radius="*radius_lg",
            input_shadow="none",
            input_shadow_dark="none",
            input_shadow_focus="*input_shadow",
            input_shadow_focus_dark="*input_shadow",
            input_text_size="*text_md",
            input_text_weight="400",
            layout_gap="*spacing_xxl",
            link_text_color="#E0AAA2",
            link_text_color_active="#F0C2BA",
            link_text_color_active_dark="#F0C2BA",
            link_text_color_dark="#E0AAA2",
            link_text_color_hover="#F8D8D0",
            link_text_color_hover_dark="#F8D8D0",
            link_text_color_visited="#D9B895",
            link_text_color_visited_dark="#D9B895",
            loader_color="*color_accent",
            loader_color_dark="*color_accent",
            panel_background_fill="#25191C",
            panel_background_fill_dark="#25191C",
            panel_border_color="#66434A",
            panel_border_color_dark="#66434A",
            panel_border_width="1px",
            panel_border_width_dark="1px",
            prose_header_text_weight="600",
            prose_text_size="*text_md",
            prose_text_weight="400",
            radio_circle="url(\"data:image/svg+xml,%3csvg viewBox='0 0 16 16' fill='white' xmlns='http://www.w3.org/2000/svg'%3e%3ccircle cx='8' cy='8' r='3'/%3e%3c/svg%3e\")",
            section_header_text_size="*text_md",
            section_header_text_weight="400",
            shadow_drop="rgba(0,0,0,0.05) 0px 1px 2px 0px",
            shadow_drop_lg="0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
            shadow_inset="rgba(0,0,0,0.05) 0px 2px 4px 0px inset",
            shadow_spread="3px",
            shadow_spread_dark="1px",
            slider_color="#C9794D",
            slider_color_dark="#C9794D",
            stat_background_fill="#B86642",
            stat_background_fill_dark="#B86642",
            table_border_color="#66434A",
            table_border_color_dark="#66434A",
            table_even_background_fill="#211619",
            table_even_background_fill_dark="#211619",
            table_odd_background_fill="#291B1F",
            table_odd_background_fill_dark="#291B1F",
            table_radius="*radius_lg",
            table_row_focus="*color_accent_soft",
            table_row_focus_dark="*color_accent_soft",
        )
